CSIC-7 Create PV workflows for NFS protocol
Infinidat/infinibox-csi-driver pull request #3
Opened 2020-02-04 10:23 UTC by gadekarnitesh

This is PR for Jira ID CSIC-7
1. Create/delete pv
2. Create/delete export rule
3.Mount/Unmount

2020-02-04 11:17 UTC, nikhilbarge requested changes

2020-02-04 11:17 UTC, nikhilbarge commented on Dockerfile
> +FROM centos:7.4.1708
use ubuntu base instead of centos

2020-02-05 08:48 UTC, nikhilbarge approved these changes

2020-02-05 09:13 UTC, Nilesh20 commented
Looks Good

2020-02-05 09:15 UTC, Nilesh20 approved these changes

2020-02-05 09:15 UTC, nikhilbarge commented
lg

2020-02-05 09:16 UTC, merged