CSIC-23_UpdateExportRule
Infinidat/infinibox-csi-driver pull request #6
Opened 2020-02-06 08:39 UTC by gadekarnitesh

PR for:

CSIC-22&CSIC-23: Update export rule on infinibox

2020-02-06 10:16 UTC, Nilesh20 requested changes

2020-02-06 10:16 UTC, Nilesh20 commented on api/nfsapiclient.go
> +			log.Errorf("fail to delete filesystem,filesystemID:%s error:%v", fileSystemID, err)
Filesystem Id is int , wil need %d i think

2020-02-07 09:49 UTC, Nilesh20 approved these changes
Looks Good

2020-02-07 09:54 UTC, nikhilbarge approved these changes
lg

2020-02-07 09:54 UTC, merged